/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAaveFlashLoanCallback,
  IAaveFlashLoanCallbackInterface,
} from "../../../contracts/FlashArbExecutor.sol/IAaveFlashLoanCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "premiums",
        type: "uint256[]",
      },
      {
        internalType: "address",
        name: "initiator",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "executeOperation",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAaveFlashLoanCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveFlashLoanCallbackInterface {
    return new Interface(_abi) as IAaveFlashLoanCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAaveFlashLoanCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAaveFlashLoanCallback;
  }
}
